name: Create Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      NODE_LATEST: 16
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 14, 16, 18 ]
        suffix: [ "" ]

    steps:
      - name: 1-checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 2-setup-image-setting
        id: setting
        run: |
          SUFFIX=""
          if [ "${{ matrix.suffix }}" != "" ]; then
            SUFFIX="-${{ matrix.suffix}}"
          fi

          TAGS="ghcr.io/${{ github.repository }}:${{ matrix.node }}$SUFFIX"
          if [ "${{ matrix.node }}" == "${{ env.NODE_LATEST }}" ]; then
            TAGS="$TAGS,ghcr.io/${{ github.repository }}:latest$SUFFIX"
          fi

          echo "current tags $TAGS"
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: 3-setup-qemu-action
        uses: docker/setup-qemu-action@v2
      - name: 4-login-action
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 5-setup-buildx-action
        uses: docker/setup-buildx-action@v2
      - name: 6-build-push-action
        uses: docker/build-push-action@v3
        continue-on-error: true
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v6
          push: true
          build-args: |
            NODE_VERSION=${{ matrix.node }}
          tags: |
            ${{ env.TAGS }}
